### ISSUE TITLE
Map without a base layer (with a custom mercator TileSource TileLayer) does not show on iOS devices

### ISSUE THREAD

**Issue by ghost** [Microsoft/BingMapsV8CodeSamples#1]
Upgrading our project from v7 to v8. Tried one of your samples on iPhone 6 with iOS 10.2.1
http://bingmapsv8samples.azurewebsites.net/Tile%20Layers/TileLayer_BaseMercator.html

Custom Tile Layer works on iOS if the base layer is included.

**Comment by rbrundritt** [comment]
I see that this question was already asked on the Bing Maps forums and is not related to an error in the samples themselves.
