### ISSUE TITLE
Error with Live V8 Code Samples Canvas Overlay

### ISSUE THREAD

**Issue by retwedt** [Microsoft/BingMapsV8CodeSamples#10]
Looking at the Canvas Overlay sample from the [Bing Maps sample code](http://bingmapsv8samples.azurewebsites.net/#Canvas%20Layer).

Getting an error loading the CanvasOverlayModule. The following is logged in the console:

```
GET http://bingmapsv8samples.azurewebsites.net/CanvasOverlayModule.js 
https://www.bing.com/rms/SDKPlugin/cj,nj/5dac24ae/265f75e7.js?bu=rms+answers+MapsSDKRelease+AnonymousBegin*SDKPluginStart*SDKInfoboxOverlay*Infobox*SDKColor*TileSource*TileLayer*Module*Layer*EntityCollection*Events*SDKPrimitiveTemplateSelector*UserMouseEventArgs*PixelReference*Pushpin*SDKPolygon*SDKPolyline*TestDataGenerator*CustomOverlay*GroundOverlay*AnimatedTileLayer*MapsTilePrimer*SDKMap*PointCompression*DeprecatedClass*SDKPluginEnd*AnonymousEnd
```

The canvas and pins aren't loading. This was working for me yesterday, looks like there was an update last night though.

Getting a similar error in my own code (using Bing Maps API w/ Webpack and Angular2), unsure what the error is here or how to debug. Please advise.

**Comment by retwedt** [comment]
Code Samples are working again.  Any direction on what that error means/how to resolve it?

**Comment by rbrundritt** [comment]
The code change yesterday simply changed how the Bing Maps keys were dynamically added to the pages. As part of that the samples where loaded differently which broke local file references in some of the samples. All fixed now.
