### ISSUE TITLE
Select Data in Drawn Polygon Area Bug

### ISSUE THREAD

**Issue by kolept** [Microsoft/BingMapsV8CodeSamples#12]
Hi Ricky, 

In Select Data in Drawn Polygon Area sample.
https://bingmapsv8samples.azurewebsites.net/#Select%20Data%20in%20Drawn%20Polygon%20Area

If you zoom out the map to maximum and draw a polygon above pacific ocean from Japan sea to North America sea area. All the pushpin will get highlighted.(Refer to picture below)

Do you know how to fix this? Is this a SDK bug or implementation bug?

Thanks,
Kolept

![bug](https://user-images.githubusercontent.com/7631918/32359168-c5ca7948-c086-11e7-8189-61e852999aac.png)

**Comment by rbrundritt** [comment]
Unfortunately this is due to a limitation in the drawing tools module. If you zoom in after drawing that polygon, you will see the polygon change shape.

**Comment by kolept** [comment]
what is the limitation ? Means the drawing tool does not support zoom out and it will simplify highlight none selected area? May I know is there any possible fix for this? I would like to only highlight selected area when zoom out the map to the max.
