### ISSUE TITLE
Getting error "More than one fragment is found in the input" while using Microsoft.Maps.GeoXmlLayer

### ISSUE THREAD

**Issue by ShahriatHossain** [Microsoft/BingMapsV8CodeSamples#17]
I am getting an exception error for using Microsoft.Maps.GeoXmlLayer and  the exception is below:

"More than one fragment is found in the input"

and I am trying to implement my code like below:

```
`var georss = '<feed xmlns="http://www.w3.org/2005/Atom" xmlns:georss="http://www.georss.org/georss"><entry><title>Sample Polygon</title><georss:polygon>46.31409 -122.22616 46.31113 -122.22968 46.31083 -122.23320</georss:polygon></entry></feed>';`
`//Load the GeoXml module.
        Microsoft.Maps.loadModule('Microsoft.Maps.GeoXml', function () {
            //Create an instance of the GeoXmlLayer.
            layer = new Microsoft.Maps.GeoXmlLayer(georss, false);

            //Add the layer to the map.
            map.layers.insert(layer);
        });`

```
I have searched a lot through google but didn't find any related solution for that error above.

Any suggestion why the error shows me. I am trying to implement this into my typescript project. But above code is working with the example of msdn standalone.

**Comment by drwestco** [comment]
This occurs when a malformed URL is encountered, specifically one with
multiple hash (#) characters. Either a href within your GeoXml content, or
the URL you're loading the content from may be malformed in this way?
