### ISSUE TITLE
getBoundary method is Queuing api calls

### ISSUE THREAD

**Issue by shohil06** [Microsoft/BingMapsV8CodeSamples#21]
Hey Team,

Seems there is an issue with Microsoft.Maps.SpatialDataService.GeoDataAPIManager.**getBoundary**() method available at [Get Multiple Boundaries](https://www.bing.com/api/maps/sdk/mapcontrol/isdk#sdsLoadMultipleBoundaries+JS) .

We tried supplying around 1000 zipcodes at one execution, while API draws boundaries of this initial request, We already triggered another request before the first one finished to the same method with another set of 1000 different zipcodes,

A strange behavior of API is observed, The api somehow caches the old requests and still loads the old set of Zipcodes even though we are supplying the new set of them.

Finally it loads it loads all two set of zipcodes i.e. 2000 in total.

Please let me know if we are doing anything wrong,

Below is the set of syntax we used.
`                    Microsoft.Maps.SpatialDataService.GeoDataAPIManager.getBoundary(latlong, geoDataRequestOptions, map, function (data) {
                        var polygon;
                        if (data.results && data.results.length > 0) {
                            map.entities.push(data.results[0].Polygons);
                            polygon = data.results[0].Polygons[0];
                            Microsoft.Maps.Events.addHandler(polygon, 'click', function () { highlight(polygon); });
                        }
                    }, polygonStyle, function errCallback(networkStatus, statusMessage) {
                        console.log(networkStatus);
                        console.log(statusMessage);
                        //alert("e");
                    });
`

Here in the above code we are supplying **latlng** as an array of zipcodes.

Any help would be appreciated.
Regards,
Shohil Sethia

**Comment by drwestco** [comment]
Let me see if I understand. You're calling getBoundary() twice, with two different sets of 1000 zipcodes? Your callback is invoked 2000 times (once for each code in each of the two sets)?

If so, the method is behaving as designed. The second call to getBoundary() doesn't cancel or replace the first.

**Comment by shohil06** [comment]
Thank You @drwestco for addressing the issue,

The scenario is,
There is a generic function which first gets 1000 zipcodes to draw, While the getboundary is still in progress, The impatient user wants to see another set of zipcodes boundaries, therefore that same generic function is called again with another set of zipcodes.

Therefore in middle of this, I am creating a new map to plot them and executing map.entities.clear() and proceeding further to draw boundaries, So ideally old set of zipcodes should not be drawn, But the opposite happens, Both are drawn now, If any third set comes before second set finishes, That will also be drawn irrespective of whether you draw a new map or clear the entities.

If and only if i wait for it to finish drawing those zipcodes and then trigger new request, Old zipcodes will not appear,

This can be confirmed here on this link [Get Multiple Boundaries](https://www.bing.com/api/maps/sdk/mapcontrol/isdk#sdsLoadMultipleBoundaries+JS)

The steps where you can check the issue:
I have uploaded two set of files in [Zipcode Set Files](https://drive.google.com/drive/folders/167qbEqn_cJOFgLPhfwFEh3PiX-5mpbbj?usp=sharing)

What one can do is, Visit [Draw Multiple Boundaries](https://www.bing.com/api/maps/sdk/mapcontrol/isdk#sdsLoadMultipleBoundaries+JS) and paste the first file code, and execute the code, and quickly paste the second file code and execute that, One will get to know the Effect that it loads both of them even after recreating the map again.

**Comment by drwestco** [comment]
Whether to show or ignore a boundary response in the callback is logic you will need to add. In your case, you want a second getBoundary() call to replace the first; others may desire the existing behavior - show all the boundaries from both calls.

One approach would be to add each boundary from a batch to its own layer, instead of the global entities collection. Then you can add/remove layers as desired to show some or all of the boundaries.

```javascript
var zipCodes = [...];
var zipCodes2 = [...];
var activeLayer;

function getBoundaries(zips) {
  var layer = new Microsoft.Maps.Layer();
  map.layers.insert(layer);
  map.layers.remove(activeLayer);
  activeLayer = layer;
	
  Microsoft.Maps.loadModule('Microsoft.Maps.SpatialDataService', function () {
    Microsoft.Maps.SpatialDataService.GeoDataAPIManager.getBoundary(zips, geoDataRequestOptions, map, function (data) {
      if (data.results && data.results.length > 0 && activeLayer === layer) {
        layer.add(data.results[0].Polygons);
      }
    });
  });
}

getBoundaries(zipCodes);
setTimeout(function () { getBoundaries(zipCodes2); }, 500);
```

**Comment by shohil06** [comment]
Hey @drwestco ,

Thank you for providing solution, I could understand that creating and replacing the new data layer does solves the problem,
But i could see the the old set set of zipcodes are still hitting the **getBoundary** API in the chrome developer tools under network tab, Though they are not populating on map, It is still blocking some bandwidth, 
Is there a way to stop them as well.

Any help would be appreciated,
Thanks !

**Comment by drwestco** [comment]
There is currently no mechanism to cancel a batch of requests made via the
getBoundary method. One possible workaround would be to issue getBoundary
calls in smaller chunks - 20 or so at a time, instead of all 1000. I think
you'd need to count the number of times callback or errorCallback is called
to know when each chunk is complete, though.

**Comment by shohil06** [comment]
Hey @drwestco ,

Thanks for providing the resolution, I figured to provide data in chunks,
Can you please provide an example for the usage with chunk counter,

Thanks & Regards,
Shohil Sethia
