### ISSUE TITLE
How can hide the Infoboxs when user click to a layer binding by GeoXML?

### ISSUE THREAD

**Issue by tranphuongyd** [Microsoft/BingMapsV8CodeSamples#24]
Hi everyone,

As the subject. I have loaded the kml data by using GeoXml module. This my code:

```
Microsoft.Maps.loadModule('Microsoft.Maps.GeoXml', function () {
	var layer = new Microsoft.Maps.GeoXmlLayer();						
	map.layers.insert(layer);
								
        layer.setDataSource('my_url', true);	
});
```

So the infobox will display when user click to an area in the map as photo below:
![image](https://user-images.githubusercontent.com/7795756/53856155-6714b280-4003-11e9-8faa-4217e9a9b4bc.png)

Now I want to suppress/hide this Infobox to show another custom popup.

Thanks,
Phuong Tran

**Comment by perfahlen** [comment]
Since you want a custom popup the easiest way is probably to handle the event yourself. Instead of setting datasource, load the data into primitives (geometries) and then you can add your own infobox

Here is an example how you can load and push it to primitives using GeoXml module
http://bingmapsv8samples.azurewebsites.net/#GeoXml%20-%20Read

Here is an example hooking up event to layer and access the primitives via layer
https://github.com/Microsoft/BingMapsV8CodeSamples/blob/master/Samples/Events/Events_RightClickShapes.html

**Comment by tranphuongyd** [comment]
Hi @perfahlen ,
Many thanks for your answer!

I have try to add the infobox to the layer as secondary example above. 
Here is my code:
```
infobox = new Microsoft.Maps.Infobox(map.getCenter(), { visible: false });
infobox.setMap(map);

//Load the GeoXml module.
Microsoft.Maps.loadModule('Microsoft.Maps.GeoXml', function () {
	layer = new Microsoft.Maps.GeoXmlLayer();						
	map.layers.insert(layer);
	
	layer.setDataSource('my_url', true);						

	Microsoft.Maps.Events.addHandler(layer, 'click', function (e) { 
		infobox.setOptions({
			location: e.location,
			description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
			visible: true
		});
	});
});
```	
But I always get 2 infobox when click to a country.
![image](https://user-images.githubusercontent.com/7795756/53871611-26cb2980-402f-11e9-8126-d5b19b55e5a0.png)

**Comment by perfahlen** [comment]
@tranphuongyd , try add the following row, after you create the layer.

layer.getOptions().suppressInfoboxes = true;

**Comment by tranphuongyd** [comment]
@perfahlen , it's ready great!
I can hide the infobox now.
I have one more concern about the zoom level. With users in China, the min zoom level always is 3. If I set to 1 or 2, the maps is not display.
Could you explain that for me?

Many thanks!

**Comment by perfahlen** [comment]
Maybe you can read something here
https://docs.microsoft.com/en-us/bingmaps/coverage/geographic-coverage

Otherwise it might be a question for the Bing maps team. I would ask that
question on Stackowerflow


ons 6 mars 2019 kl. 10:30 skrev tranphuongyd <notifications@github.com>:

**Comment by tranphuongyd** [comment]
@perfahlen , many thanks for your help!

**Comment by IoTGirl** [comment]
You might want to try saving resources and reusing the same infobox if you only want one at a time.  See [https://www.bing.com/api/maps/sdk/mapcontrol/isdk/reuseinfobox](https://www.bing.com/api/maps/sdk/mapcontrol/isdk/reuseinfobox)

Note: If your issue has been addressed please close your question.

**Comment by IoTGirl** [comment]
no response - please reopen if you are still seeing this issue.
