### ISSUE TITLE
Clustering_PushpinList: Single pushpins are not clickable after interacting with the map

### ISSUE THREAD

**Issue by jengeb** [Microsoft/BingMapsV8CodeSamples#3]
Thanks for providing all code samples. 

After loading the map all pushpins - both clustered and single pushpins - can be clicked and an infobox appears after clicking. 

Unfortunately the non-clustered pushpins are not clickable anymore after interacting with the map (dragging, zooming in/out). 

It would be very handy if this feature could be added to the `Clustering_PushpinList.html` example.

**Comment by rbrundritt** [comment]
This is a known bug in the Bing Maps V8 API which is fixed in the experimental branch. The main release branch will be updated at the end of the month.

**Comment by jengeb** [comment]
Thanks for your answer!

**Comment by rbrundritt** [comment]
I've modified the code sample to attach the click events to the layer rather than the pushpins themselves. This gets rid of the issue.
