### ISSUE TITLE
ROBUX Scam??

### ISSUE THREAD

**Issue by LolalrikofficialYT** [Microsoft/BingMapsV8CodeSamples#31]
Why Why Why Microsoft did u remove the free robux , and also its not fair that u guys are not allowing other countries to have it. Is this a joke , I waited on ur website for 3 hours after I received the free 100 robux but it showed me an error , and it said that this product is unavailable , wtf is wrong with guys , pls send me the robux code  ASAP, 
I have the right to get it cause I did all the steps . Send me the code here : ralrik31@outlook.com , I better see my robux code in my outlook email by tommorow 31/12/2020

It better be there 😠

I did not sit there in ur stupid website for 3 hours  to see this error.

**Comment by rbrundritt** [comment]
This is definitely not the right place for this complaint. I don't even know what Robux is lol. 

Try one of these feedback options:

https://www.microsoft.com/en-us/feedback

https://answers.microsoft.com/en-us/feedback/forum

**Comment by IoTGirl** [comment]
@LolalrikofficialYT Ricky is correct. This is not the correct place to get support. Please go to https://www.microsoft.com/en-us/rewards/robux-offer and sign in then scroll to the bottom of the page to choose support.

Note: You can join the discussion here: https://answers.microsoft.com/en-us/bing/forum/all/free-100-robux-digital-code/350d4488-f077-467c-9955-48f487aef769
