### ISSUE TITLE
bing map draw shape with angular13

### ISSUE THREAD

**Issue by vivek-vekariya** [Microsoft/BingMapsV8CodeSamples#32]
i want to add draw shape and find the area of it in bing map using angular13 is it possible in typescript?
like this screenshot
<img width="888" alt="191280-capture" src="https://user-images.githubusercontent.com/80434608/162445182-8e9c80b7-87ac-4b19-9952-aef30fcec3b7.png">

**Comment by drwestco** [comment]
There are a couple of parts to this:
1. Getting the shapes from the Drawing module (https://docs.microsoft.com/en-us/bingmaps/v8-web-control/map-control-concepts/drawing-tools-module-examples/get-shapes-from-drawingmanager)
2. Calculating the area or perimeter of the shape (https://docs.microsoft.com/en-us/bingmaps/v8-web-control/modules/spatial-math-module/geometry-calculations)

**Comment by vivek-vekariya** [comment]
I go through that article and i used same code. for my project but 

  ```
 Microsoft.Maps.loadModule(['Microsoft.Maps.DrawingTools', 'Microsoft.Maps.SpatialMath'], function () {
      this.drawingLayer = new Microsoft.Maps.Layer();
      debugger;
      this.map.layers.insert(this.drawingLayer);
      debugger;
      this.tools = new Microsoft.Maps.DrawingTools(this.map);
      debugger;
      this.toolsPolyline = new Microsoft.Maps.DrawingTools(this.map);
    });
```

but, while run  the project debugger not hit and variables becomes empty and that cause an error in my project and not work properly, any solution for that?


<img width="957" alt="Capture" src="https://user-images.githubusercontent.com/80434608/162675488-7247598e-f490-44c5-8956-41f6d5ce0947.PNG">
