### ISSUE TITLE
[Accessibility] Luminosity ratio of "Microsoft Bing" link text with its background color is less than 4.5:1 on the screen.

### ISSUE THREAD

**Issue by cdhawan** [Microsoft/BingMapsV8CodeSamples#34]
Low visible user will face difficulty in identifying the text appearing on the control if the luminosity ratio of text color to its background color is less than 3:1.

![image](https://user-images.githubusercontent.com/16544183/166344520-3de9aa60-00d1-48a6-9d1d-23a52590f9d5.png)

**Comment by drwestco** [comment]
This repo is for the V8 Code Samples code snippets, not the Bing Map SDK control itself. Please use the feedback mechanism within Bing Maps to report this issue.
