### ISSUE TITLE
Event when shape drawing is complete?

### ISSUE THREAD

**Issue by thor-schueler** [Microsoft/BingMapsV8CodeSamples#5]
@rbrundritt: we are using bing maps to display a large number of shapes (markers, lines, polygons) using x-maps. We have thousands of shapes and performance is pretty good as we stream that data onto the map. However, right now we have no reliable way to let the user know that all drawing has been completed. We know when we sent all data to the map, but there is some latency, sometimes more than a few seconds before all the drawing on the canvas is complete. During that time, the map is essentially locked up as drawing commences. 

None of this is terrible, but we would like to display a visual indication that loading/drawing is in progress. Is there an event that is raised once the map has entered into an idle state where all map operations (zooming, drawing, panning, etc).  have completed? I could not find anything in the reference. 

Google Maps has an 'idle' event that does some of that, (from my testing, it does not take drawing operations into consideration).

**Comment by rbrundritt** [comment]
There is no event that occurs when this is done. The map control is async based and data is rendered as tiles for performance. Each tile is loaded on its own and ignorant of other tiles. So, not sure if there is a way capture a drawing complete type event for the map. You could use a throttled viewchangeend event which would fire after the map is moved. Throttling it would cause the event to fire after the map has stopped moving and the drawing has started. The drawing process may block the throttled code from running until the UI thread is available. Will add a feature request for something along these lines and see what the engineering team thinks.
