### ISSUE TITLE
HTMLPushPin Layer not displaying 

### ISSUE THREAD

**Issue by rollasoc** [Microsoft/BingMapsV8CodeSamples#6]
I have downloaded the example code and it works as is (other than point 2 below).   

1) 
If I amend the code to default to the UK and change the map type, using setView.  The pins are no longer displayed.

```
var zoomOptions=	{
			mapTypeId: Microsoft.Maps.MapTypeId.aerial,
			zoom: 5,
			center: new Microsoft.Maps.Location(54, -2)		};
		
		map.setView(zoomOptions);
```

Adding more pins and clicking "Bring into View", moves the map, so I can see the items are in the layer.  They are just not being displayed.  Not sure if this is a timing issue?

if I take out the line
`mapTypeId: Microsoft.Maps.MapTypeId.aerial,`

and refresh they appear.  Changing the Map Type to Aerial works using the map controls.  Just not if I set it in code.  (the map type changes, but the pins are no longer visible).

2) The hover label, doesn't appear to be showing the infobox.

**Comment by rbrundritt** [comment]
The issue is that some additional functionality was added which used new features for a V8 release that went out, but then got rolled back. Set the branch to experimental and it will work. The V8 release should be going out again in a couple weeks after some additional testing is done.
