### ISSUE TITLE
polygon shape get back to it's after editing finished.

### ISSUE THREAD

**Issue by hiteshhilok** [Microsoft/BingMapsV8CodeSamples#7]
Drawing tools looks promising, i found a bug, when user create polygon it works perfectly, as we use it in edit mode, it gives some js error, 
 TypeError: Cannot set property 'alpha' of undefined at Function.n._createTemplate

I believe due to this, after finishing edit, polygon get back it's initial shape.

**Comment by rbrundritt** [comment]
Can you provide more details, it isn't clear what you are doing. I'm not able to reproduce any issues. Note, that if you want to modify any shape that is in the drawing manager, you need to take it out of the manager, modify it, then add it back in. There are several samples for the drawing tools which do this. Take a look through them if you haven't already.

**Comment by hiteshhilok** [comment]
thanks for getting me back,

Issue is, when i can create polygon using polygon shape button, it work good, In edit mode , it allow me to change position of points, after adjusting points, i am not able to save it , as give me intial shape instead of updated.

**Comment by perfahlen** [comment]
Hi,
I provided a simple drawing project in typescript. It works as excepted by drawing a polygon, modified it and keep the modied geometry. Hopefully it helps you move forward.

[BMDraw.zip](https://github.com/Microsoft/BingMapsV8CodeSamples/files/1328873/BMDraw.zip)

**Comment by hiteshhilok** [comment]
thanks perfahlen,
