### ISSUE TITLE
Map image generator giving security error in IE

### ISSUE THREAD

**Issue by sasi210891** [Microsoft/BingMapsV8CodeSamples#8]
i'm using map image generator to get map as image, it is working fine in Chrome and Firefox. giving security error in IE.

**Comment by rbrundritt** [comment]
The sample works fine on IE11 when I test this: http://bingmapsv8samples.azurewebsites.net/#Map%20Image%20Generator

If you have any custom pushpin images, or tile layers that are not hosted on the same domain as your site, you will get a security message.

**Comment by sasi210891** [comment]
Finally I managed to find the issue. I'm using svg as custom push pin. IE is not allowing convert map with svg to image.

**Comment by rbrundritt** [comment]
Good find. Looks like this is limited to IE. Another good example of why we made this code sample rather than a built in feature.
