### ISSUE TITLE
Question on editing complex polygons

### ISSUE THREAD

**Issue by thor-schueler** [Microsoft/BingMapsV8CodeSamples#9]
@rbrundritt : we've been playing around with implementing poly editing in angular-maps. Pretty straight forward, but we noticed that for complex polys, only the first ring seems to be editable. Is that by design or is that a bug? 

Also, we had a complex poly where one of the inner rings had less than 3 points (result of data optimization algorithm). While this does not break the rendering of the poly, it does break the editing for the entire poly. Definitely a data error on our part, but I thought I point it out so you can perhaps consider making it more robust.

**Comment by rbrundritt** [comment]
Has the dev team look into this. This is a fairly large work item and since this is the only request for this, it will be considered low priority for now, so may take some time for the team to get to this.
